// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKtzoson40jiYPAoUaSl5yDRNPNLxn56k',
    appId: '1:355216699206:web:acbd0b48ed8ffb96e47f47',
    messagingSenderId: '355216699206',
    projectId: 'hgoceryapp',
    authDomain: 'hgoceryapp.firebaseapp.com',
    storageBucket: 'hgoceryapp.firebasestorage.app',
    measurementId: 'G-GZZ28QP4R7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmKS-U1SlNb80f_Wp2rbou6-BsRwV7CvY',
    appId: '1:355216699206:android:a494e6eae8005d75e47f47',
    messagingSenderId: '355216699206',
    projectId: 'hgoceryapp',
    storageBucket: 'hgoceryapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBO9uGhtQ0ed2W0Qb1zpCL7xIMsdG4GtY',
    appId: '1:355216699206:ios:7a4621d0c0c7abcfe47f47',
    messagingSenderId: '355216699206',
    projectId: 'hgoceryapp',
    storageBucket: 'hgoceryapp.firebasestorage.app',
    androidClientId: '355216699206-6vrtbi2v2dqhm20ob24fki4voc0on05i.apps.googleusercontent.com',
    iosClientId: '355216699206-jm75doaogsaigvle4ciknbbdqu36855r.apps.googleusercontent.com',
    iosBundleId: 'com.HGM.hgoceryWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBO9uGhtQ0ed2W0Qb1zpCL7xIMsdG4GtY',
    appId: '1:355216699206:ios:7a4621d0c0c7abcfe47f47',
    messagingSenderId: '355216699206',
    projectId: 'hgoceryapp',
    storageBucket: 'hgoceryapp.firebasestorage.app',
    androidClientId: '355216699206-6vrtbi2v2dqhm20ob24fki4voc0on05i.apps.googleusercontent.com',
    iosClientId: '355216699206-jm75doaogsaigvle4ciknbbdqu36855r.apps.googleusercontent.com',
    iosBundleId: 'com.HGM.hgoceryWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKtzoson40jiYPAoUaSl5yDRNPNLxn56k',
    appId: '1:355216699206:web:d1856b1057d0ce11e47f47',
    messagingSenderId: '355216699206',
    projectId: 'hgoceryapp',
    authDomain: 'hgoceryapp.firebaseapp.com',
    storageBucket: 'hgoceryapp.firebasestorage.app',
    measurementId: 'G-42H050P9GG',
  );
}
